//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProject {
    
    
    public partial class SignUp {
        
   
        protected global::System.Web.UI.HtmlControls.HtmlForm SignUpPage;
        
   
        protected global::System.Web.UI.WebControls.TextBox loginEmail;
        
      
        protected global::System.Web.UI.WebControls.TextBox loginPassword;
        
     
        protected global::System.Web.UI.WebControls.Button loginUserName;
        
   
        protected global::System.Web.UI.WebControls.TextBox sName;
        
    
        protected global::System.Web.UI.WebControls.TextBox sBirthDate;
        
      
        protected global::System.Web.UI.WebControls.TextBox sEmail;
    
        protected global::System.Web.UI.WebControls.TextBox sPassword;
        
      
        protected global::System.Web.UI.WebControls.TextBox scPassword;
        
    
        protected global::System.Web.UI.WebControls.TextBox Phone;
   
        protected global::System.Web.UI.WebControls.TextBox Address;
    }
}
